### PR TITLE
fix: visibility toggle + redirect on save

### LINKED ISSUE #224: Frontend: Fix Career Profile visibility toggle not reflecting saved preference
Upon toggling the Career Profile visibility option and subsequently hitting "Save Changes", the toggle will revert back to the pre-saved state preference. In my testing, this issue occurs only on the frontend - data is persisted as intended in the db.

https://private-user-images.githubusercontent.com/91710711/572808591-424b9198-da57-4fd3-bb8d-a6f89b60fc59.mov?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NzUxNjQyODgsIm5iZiI6MTc3NTE2Mzk4OCwicGF0aCI6Ii85MTcxMDcxMS81NzI4MDg1OTEtNDI0YjkxOTgtZGE1Ny00ZmQzLWJiOGQtYTZmODliNjBmYzU5Lm1vdj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNjA0MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjYwNDAyVDIxMDYyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU3ODRjNTFiMmY5YzFjOGJiMjcxNGQxYWE3ZmE3ZGJjN2JjN2ZiNjBiZjJkMDVjNDk4MTlkZTA1ZGNhZmU3NjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.6jafVLTPk91svR33inC4FRaRIG6HlQwShOLhKz2kYBc

### PR DESCRIPTION
**Pull request by RyloRiz**
## Description

Fixes career profile visibility toggle not persisting toggled state on the frontend (plus a minor .eslintrc.js property fix)

## Related Issue

Resolves #224 

## Steps to view & test changes:

- Checkout latest `internship-main` on `membership-portal` & `membership-portal-deployment`
- Checkout `fix/career-toggle` on `membership-portal-ui`
- Run dev server
- Edit career profile & hit Save Changes

## How Has This Been Tested?

- [x] Manual tests
- [ ] Responsive View

### CODE REVIEW

File: src/components/Profile/CareerProfile.jsx [hunk 1]
```diff
@@ -87,15 +87,16 @@ export default class CareerProfile extends React.Component {
         resumeUrl: this.props.profile.resumeUrl || '',
         skills: this.props.profile.skills || [],
         careerInterests: this.props.profile.careerInterests || [],
-        isProfilePublic: this.props.profile.isProfilePublic !== undefined ? this.props.profile.isProfilePublic : true,
+        // Below line caused profile visibility toggle to reset, leading to confusion
+        // isProfilePublic: this.props.profile.isProfilePublic !== undefined ? this.props.profile.isProfilePublic : true,
```
Comment (smalex-z) [inline src/components/Profile/CareerProfile.jsx]: we can probably just remove this right

File: src/components/Profile/CareerProfile.jsx [hunk 2]
```diff
@@ -203,7 +206,10 @@ export default class CareerProfile extends React.Component {
     try {
       await this.props.updateCareerProfile(updates);
       this.setState({ saving: false, saveSuccess: true });
-      setTimeout(() => this.setState({ saveSuccess: false }), 3000);
+      setTimeout(() => {
+        this.setState({ saveSuccess: false });
+        window.location.replace('/profile/career');
```
Comment (smalex-z) [inline src/components/Profile/CareerProfile.jsx]: `history.push('/profile/career')` might be better here

File: src/components/Profile/CareerProfile.jsx [hunk 3]
```diff
@@ -203,7 +206,10 @@ export default class CareerProfile extends React.Component {
...
+      }, 1000);
```
Comment (smalex-z) [inline src/components/Profile/CareerProfile.jsx]: 1 second might be too aggressive, might be better as 2 or 3 seconds

**Review by smalex-z — APPROVED** [review]
very small things! up to you whether you want to implement or not

File: src/components/Profile/CareerProfile.jsx (hunk 1 above)
Comment (RyloRiz) [reply src/components/Profile/CareerProfile.jsx]: Yeah I had kept for anyone reading the changes

File: src/components/Profile/CareerProfile.jsx (hunk 2 above)
Comment (RyloRiz) [reply src/components/Profile/CareerProfile.jsx]: That's what it was I forgot

File: src/components/Profile/CareerProfile.jsx (hunk 3 above)
Comment (RyloRiz) [reply src/components/Profile/CareerProfile.jsx]: I tried all of those & my personal preference was 1s, but if you wanna bump it up idm

**Comment by RyloRiz** [comment]
Don't merge yet my VSCode Git tab bugging & screwing up the commits

**Comment by RyloRiz** [comment]
Alright we're good

**Comment by smalex-z** [comment]
@RyloRiz lgtm feel free to merge
